AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Resources:
  CreateDynamoDBTable:
    Type: AWS::DynamoDB::Table # type goes here
    Properties:
    # props go here
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
    # look for every one that is required
      AttributeDefinitions:
        - AttributeName:  Foo
          AttributeType:  S
      KeySchema:
        - AttributeName: Foo # has to be one of the above
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  AddToDynamoFunction:
    Type: AWS::Serverless::Function # created me a lambda
    Properties:
      Handler: index.test
      Runtime: nodejs6.10
      CodeUri: .
