AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AddToDynamoFunction:
    Properties:
      CodeUri: s3://dynamo-db-bucket/c4c59dc6cd61bbd3dadeb582cbc2438e
      Handler: index.myLambda
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  CreateDynamoDBTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: CUSTOMER_ID
        AttributeType: S
      KeySchema:
      - AttributeName: CUSTOMER_ID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: CustomerTable
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
