AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AddToDynamoFunction:
    Properties:
      CodeUri: s3://dynamo-db-bucket/1bca043d7e13f0a314f66688a03f3a88
      Handler: index.myLambda
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  CreateDynamoDBTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: CUSTOMER_ID
        AttributeType: N
      KeySchema:
      - AttributeName: CUSTOMER_ID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
